kind: pipeline
name: linux-amd64-sonarqube-scanner
type: vm

platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: pr test java
    image: plugins/docker:20
    settings:
      daemon_off: false
      dockerfile: Dockerfile
      repo: plugins/sonarqube-scanner
      dry_run: true
    when:
      ref:
        - "refs/pull/**" # Only run for pull requests
  - name: publish-2.1.2
    image: plugins/docker:20
    settings:
      # auto_tag: true
      # auto_tag_suffix: v2.0.2-java17
      tags:
        - v2.1.2
        # - latest
        # - stable-java17
      daemon_off: false
      dockerfile: Dockerfile
      password:
        from_secret: docker_password
      repo: plugins/sonarqube-scanner
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"
    - "refs/pull/**"
