kind: pipeline
name: linux-amd64-sonarqube-scanner
platform:
  os: linux
  arch: amd64
steps:
- name: publish
  image: plugins/docker:19
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    daemon_off: false
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: plugins/sonarqube-scanner
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
trigger:
  event:
  - push